## helm3 template --set global.env=oman,global.mode.standard=false,global.namespace.prefix=oman,global.namespace.mid=fluxble,global.host.prefix=oman,global.host.baseUrl=fluxble.com ./
global:
  nsPrefix: dev-meeraspace
  baseUrl: dev.meeraspace.com
  gateway: default/gateway
  hostPrefix: 
  hostSuffix: 
# nameOverride: CHANGEME-APPNAME
nameOverride: CHANGEME
envs:
  enabled: true

## set up the DependenciesSvcName, base on requirements.yaml
DependenciesSvcName:
  ## If false, DependenciesSvc will not be installed
  ## If true, DependenciesSvc will  be installed, and then exec ` helm dependency update . `
  # enabled: true
  enabled: false

# fullnameOverride: 

job:
  initdb:
    enabled: false
apiVersion:
  Deployment: apps/v1
  StatefulSet: apps/v1
  VirtualService: networking.istio.io/v1alpha3
  Service: v1
  Secret: v1
  PersistentVolumeClaim: v1

# kind: it can be Deployment or StatefulSet
kind: Deployment
replicaCount: 1
podAnnotations: {}
#enabled/disable istio-sidecar
  # sidecar.istio.io/inject: "false"
initContainer:
  enabled: false
  repository: CHANGEME-REPO
  tag: latest
  pullPolicy: Always
  extraCommand: {}
  extraEnv: {}
  extraENVRulehandled: {}
  volumeMounts:
  ## If true,  pod volumes to mount into the container's filesystem
    enabled: false
    volumeMounts:
      - name: CHANGEME-PodVolumeName
        mountPath: CHANGEME-initContainerPath
image:
  repository: CHANGEME-REPO
  tag: "latest"
  pullPolicy: Always
  # pullPolicy: IfNotPresent
  # ports:
  # - name: http
  #   containerPort: CHANGEME-PORT
  #   protocol: TCP

  extraCommand: []
  optionalCommand: []

  ## envFrom  configMapRef:
  ## Predefined global variables `comfigmap-envvars.yaml`，import the container by envFrom: - configMapRef: 
  envFromConfigMap:
    enabled: false
  
  extraEnv: {}

  optionalEnv: {}

  extraENVRulehandled: {}


  extraENVRulehandled2: {}
    # manually-registered-apps: 1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16-17-18-19-41-42

  extraEnvFromSecert:

service:
  # type: ClusterIP
  # ports:
  # - port: CHANGEME
  #   name: http
  #   targetPort: CHANGEME

istio:
  virtualservice:
    enabled: false
    host: 
    http:
    - match:
      - uri:
          prefix: /CHANGEME-PATH
      - uri:
          prefix: /CHANGEME-PATH2
      route:
      - destination:
          host: CHANGEME-HOST
          port:
            number: CHANGEME-PORT

  virtualserviceGrpc:
    enabled: false
    host: grpc
    http:
    - match:
      - uri:
          prefix: /target.grpc.CHANGEME.CHANGEME/
      route:
        - destination:
            host: CHANGEME-GRPC-SVC
            port:
              number: CHANGEME-GRPC-PORT

  virtualserviceGrpcMtls:
    enabled: false


resources: {}

## ref: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
# priorityClassName:

nodeSelector:

tolerations: []

affinity: {}

volumeMounts:
  ## If true,  Pod volumes to mount into the container's filesystem
  enabled: false
  volumeMounts:
    - name: configmap
      mountPath: /config.yaml
      subPath: dex-config
    # - name: pvc-data
    #   mountPath: /usr/local/static      
    # - name: configmap
    #   mountPath: CNGNAME
    #   subPath: CNGNAME

volumes:
  ## If true, will create/use a Volume, configmap nfs hostPath emptyDir
  # enabled: false
  ## if type is configmap, will auto use the configmap value by  `name: {{ template "APP.fullname" . }}-config`
  useconfigmap:
    enabled: false
  volumes:
  # - name: datadir
  #   emptyDir: {}
  #   volumes:
  # - name: pvc-data
  #   persistentVolumeClaim:
  #     claimName: pvc-data



persistentVolumeClaim1:
  ## If true,  will create/use a Persistent Volume Claim
  enabled: false
  # Whether to enable volumeClaimTemplates, only for StatefulSet
  volumeClaimTemplate:
    enabled: false
  name: pvc-date   # same to volumes.volumes.volumesvolumes.claimName
  ## supported values: "ReadOnlyMany", "ReadWriteMany", "ReadWriteOnce"
  accessModes:
    - ReadWriteOnce
  annotations: {}
  # existingClaim: ""
  size: 1Gi
  storageClass: "standard"

# tolerations:
# - key: allowspot
#   operator: Equal
#   value: "true"
# 单实例分配到spot,多实例只有一个分配到spot
# affinity:
#   nodeAffinity:
#     preferredDuringSchedulingIgnoredDuringExecution:
#     - weight: 1
#       preference:
#         matchExpressions:
#         - key: node
#           operator: In  #Try to deploy to the SPOT node
#           values:
#           - spot
#   podAntiAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#     - labelSelector:
#         matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - CHANGEME_APPNAME
#       topologyKey: "kubernetes.io/hostname"