{{- if .Values.istio.virtualserviceGrpc.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "APP.name" . }}-grpc
spec:
{{- if  not .Values.istio.virtualserviceGrpc.host  }}
  hosts:
  - grpc.{{ .Values.global.baseUrl }}
{{- else }}
  hosts:
  - {{ .Values.istio.virtualserviceGrpc.host }}.{{ .Values.global.baseUrl }}
{{- end }}
  gateways: 
  - {{ .Values.global.gateway }}
  http:
{{ toYaml .Values.istio.virtualserviceGrpc.http | indent 2 }}
{{- end -}}