apiVersion: v1
kind: Secret
metadata:
  name: {{ template "APP.name" . }}-gitlabregistrykey
  labels:
    app: {{ template "APP.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: "kubernetes.io/dockerconfigjson"
data:
{{- range .Files.Lines "Files/registrySecret.txt" }}
  {{ . }}{{ end }}
