variables:
  APP_CHART_NAME: audit-trail-service ## replace the right chart name
  RELEASE_NAME: audit-trail-service
  KUBECONFIG: /etc/deploy/config
  HELM_REPO_TARGET: https://chartmuseum.target.meeraspace.com/
  HELM_REPO_DEV: https://chartmuseum.dev.meeraspace.com/

  DOCKER_DRIVER: overlay2

stages:
  #- test
  - deploy_audit_common
  - build
  - deploy_to_dev
  - push_incubator_chart
  - deploy_to_test
  #- push_stable_chart
  #- release_request
  #- deploy_to_staging
  #- deploy_to_demo
  #- deploy_to_prod

include:

  - remote: https://target-digital-transformation.gitlab.io/pipeline/01_build_reuse_image.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/02_v2_deploy_to_dev.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/03_v2_push_Incubator_chart.yml
  - remote: https://target-digital-transformation.gitlab.io/pipeline/04_v2_deploy_to_test.yml
  #- remote: https://target-digital-transformation.gitlab.io/pipeline/05_v2_push_stable_chart.yml
  #- remote: https://target-digital-transformation.gitlab.io/pipeline/06_v2_release_request.yml
  #- remote: https://target-digital-transformation.gitlab.io/pipeline/07_v2_deploy_to_staging.yml
  #- remote: https://target-digital-transformation.gitlab.io/pipeline/07_v2_deploy_to_prod_odp_azure.yml
  #- remote: https://target-digital-transformation.gitlab.io/pipeline/07_v2_deploy_to_prod_eks_fluxble.yml



#test-coverage:
#  image: golang:1.11.2-alpine3.8
#  stage: test
#  script:
#    - mkdir -p /go/src/gitlab.com/target-digital-transformation
#    - ln -s ${PWD} /go/src/gitlab.com/target-digital-transformation
#    - apk add --no-cache git build-base
#    - cd /go/src/gitlab.com/target-digital-transformation/sso
#    - go test ./... -v -coverprofile .testCoverage.txt
#  except:
#    - tags 

Deploying audit common:
  image: maven:3-jdk-8
  stage: deploy_audit_common
  only:
    - develop
  cache:
     paths:
        - .m2/
  script:
  - "cd auditcommon"
  - "mvn clean install deploy -s ../settings.xml"
  artifacts:
    paths:
      - target/*.jar
  allow_failure: false

build_image:
  extends: .build_single_image
  stage: build
  variables:
    DOKCERFILE_NAME: Dockerfile
  only:
    - develop
    - tags
  tags:
    - woking-physical   

dev.meeraspace.com:
  extends: .deploy_to_dev_v2
  variables:
    ##   helm3 install [RELEASE_NAME] [APP_CHART_NAME] -n [NAMESPACE] --set 
    RELEASE_NAME: audit-trail-service
    NAMESPACE: dev-meeraspace-wasl
    environment_name: dev
    environment_url: https://dev.meeraspace.com
    nsPrefix: dev-meeraspace
    baseUrl: dev.meeraspace.com
    gateway: default/gateway
  script:
    - >
      echo "helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.env=${environment_name} \
        --set image.repository=$CI_REGISTRY_IMAGE/${CI_COMMIT_REF_SLUG} \
        --set-string image.tag=${CI_COMMIT_SHA:0:8} \
        --debug --wait ./"
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.nsPrefix=${nsPrefix},global.baseUrl=${baseUrl},global.gateway=${gateway} \
        --set image.repository=$CI_REGISTRY_IMAGE/${CI_COMMIT_REF_SLUG} \
        --set-string image.tag=${CI_COMMIT_SHA:0:8} \
        --debug --wait ./

  only:
    - develop
  tags:
    - woking-physical
  #when: manual

push_incubator_chart:
  extends: .push_incubator_chart_v2
  #tags:
  #  - ankara-office
  #when: manual    

test.meeraspace.com:
  extends: .deploy_to_test_v2
  variables:
    NAMESPACE: test-meeraspace-wasl
    environment_name: test
    environment_url: https://test.meeraspace.com
    nsPrefix: test-meeraspace
    baseUrl: test.meeraspace.com
    gateway: default/gateway

  script:
    #- sed -i "s#/mnt/target-dev-nfs#/mnt/target-test-nfs#" values.yaml
    #- sed -i "s#/mnt/target-dev-nfs/server-files#/mnt/target-test-nfs/server-files#" values.yaml
    - >
      helm3 upgrade ${RELEASE_NAME} -n ${NAMESPACE} \
        --set global.baseUrl=${baseUrl} \
        --set global.nsPrefix=${nsPrefix} \
        --debug --wait ./
  when: manual
 
## after pass the acceptance test
#push_stable_chart:
#  extends: .push_stable_chart
#  only:
#    - tags
# # tags:
# #   - dev-meeraspace
#  when: manual 

#release_request:
#  extends: .release_request
  
#deploy_to_staging_internal:
#  extends: .deploy_to_staging_internal

#deploy_to_demo_aws:
#  extends: .deploy_to_demo_aws
#  only:
#    - tags
#  tags:
#    - dev-meeraspace
#  when: manual 

## It is not actually deployed, just used to mark the state
# deploy_to_internnal:
#   extends: .deploy_to_prod
#   only:
#   - tags
#   - triggers 
