apiVersion: v2
appVersion: 27.02.26
dependencies:
- alias: common
  condition: common.enabled
  name: common
  repository: file://../common
  version: 0.2.6
- alias: common2
  condition: common2.enabled
  name: common
  repository: file://../common
  version: 0.2.6
description: A Helm chart for trove-api
keywords:
- trove-api
name: trove-api
sources:
- A list of URLs to source code for this project (optional)
version: 27.02.26
