{{ if eq .Values.kind "Deployment" }}
apiVersion: {{ .Values.apiVersion.Deployment }}
{{ else if eq .Values.kind "StatefulSet"}}
apiVersion: {{ .Values.apiVersion.StatefulSet }}
{{- end }}
kind: {{ .Values.kind }}
metadata:
  name: {{ template "APP.name" . }}
  labels:
    app: {{ template "APP.name" . }}
    version: {{ template "APP.version" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{if eq .Values.kind "StatefulSet"}}
  serviceName: {{ template "APP.name" .}}-headless
  {{- end }}
  {{- if and (eq .Values.kind "Deployment") .Values.persistentVolumeClaim1.enabled }}
  strategy: 
    type: Recreate
  {{- end }}

  selector:
    matchLabels:
      app: {{ template "APP.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations: 
{{ toYaml .Values.podAnnotations | indent 8 }}
      labels:
        app: {{ template "APP.name" . }}
        release: {{ .Release.Name }}
        version: {{ template "APP.version" . }}
        env: {{ .Values.global.nsPrefix }}
    spec:
      imagePullSecrets:
      - name: {{ .Release.Name }}-gitlabregistrykey
      containers:
        - name: {{ template "APP.name" . }}
          image: "{{ template "APP.imageName" .}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.image.envFromConfigMap.enabled }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          {{- end }}          
          env:
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace          
  {{- $baseUrl := .Values.global.baseUrl -}}
  {{- $nsPrefix := .Values.global.nsPrefix -}}
          {{- range $key, $value := .Values.image.extraENVRulehandled }}
          - name: {{ $key }}
            value: {{ printf $value | replace "$baseUrl" $baseUrl | replace "$nsPrefix" $nsPrefix | quote }}
          {{- end }}
          {{- range $key, $value := .Values.image.extraENVRulehandled2 }}
          - name: {{ $key }}
            value: {{ printf $value | replace "-" "," }}
          {{- end }}
          {{- range $key, $value := .Values.image.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- range $key, $value := .Values.image.optionalEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.envs.enabled }}
          args:
          {{- else }}
          command:
          {{- end }}
          {{- range $key, $value := .Values.image.extraCommand }}
          - {{ $value | quote }}
          {{- end }}
          {{- with .Values.image.optionalCommand }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
  {{- if .Values.image.ports }}
          ports:
{{ toYaml .Values.image.ports | indent 10 }}
  {{- end }}
{{- if  .Values.volumeMounts.enabled }}
          volumeMounts:
{{ toYaml .Values.volumeMounts.volumeMounts | indent 12 }}  
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}  
          livenessProbe:
{{ toYaml .Values.livenessProbe | indent 12 }}
          readinessProbe:
{{ toYaml .Values.readinessProbe | indent 12 }}
{{- if .Values.volumeMounts.enabled }}
      volumes:
{{- if .Values.volumes.useconfigmap.enabled }}
      - name: configmap
        configMap:
          name: {{ .Release.Name }}-configmap
{{- end }}
{{- if .Values.volumes.volumes }}
{{ toYaml .Values.volumes.volumes | indent 6 }}
{{- end }}   
{{- end }}  

{{- if and  (eq .Values.kind "StatefulSet")  .Values.persistentVolumeClaim1.volumeClaimTemplate.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Values.persistentVolumeClaim1.name }}
    spec:
      accessModes:
    {{ toYaml .Values.persistentVolumeClaim1.accessModes | indent 4 }}
      resources:
        requests:
          storage: "{{ .Values.persistentVolumeClaim1.size }}"
      storageClassName: "{{ .Values.persistentVolumeClaim1.storageClass }}"
{{- end -}}
    {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- if .Values.initContainer.enabled }}
      initContainers:
        - name:  {{ template "APP.name" . }}-init
          image: "{{ .Values.initContainer.repository }}:{{ .Values.initContainer.tag }}"
          imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
{{- if  .Values.initContainer.volumeMounts.enabled }}
          volumeMounts:
{{ toYaml .Values.initContainer.volumeMounts.volumeMounts | indent 12 }}
{{- end }}
          env:
          {{- range $key, $value := .Values.initContainer.extraENVRulehandled }}
          - name: {{ $key }}
            value: {{ printf $value | replace "$baseUrl" $baseUrl | replace "$nsPrefix" $nsPrefix | quote }}
          {{- end }}
          {{- range $key, $value := .Values.initContainer.extraENVRulehandled2 }}
          - name: {{ $key }}
            value: {{ printf $value | replace "-" "," }}
          {{- end }}
          {{- range $key, $value := .Values.initContainer.extraEnv }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- if .Values.envs.enabled }}
          args:
          {{- else }}
          command:
          {{- end }}
          {{- range $key, $value := .Values.initContainer.extraCommand }}
          - {{ $value | quote }}
          {{- end }}
{{- end -}}