{{- if .Values.istio.virtualserviceGrpcMtls.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "APP.name" . }}-grpc
spec:
  hosts:
  - {{ template "hostUrl" . }}
  gateways: 
  - {{ template "GATEWAY.addr" . }}
  http:
{{ toYaml .Values.istio.virtualserviceGrpcMtls.http | indent 2 }}
{{- end -}}