## helm3 template --set global.env=oman,global.mode.standard=false,global.namespace.prefix=oman,global.namespace.mid=fluxble,global.host.prefix=oman,global.host.baseUrl=fluxble.com ./
global:
  nsPrefix: dev-meeraspace
  baseUrl: dev.meeraspace.com
  gateway: default/gateway

# fullnameOverride:

replicaCount: 1

configmap:
  enabled: false

  configurationFiles:
    #dex-config: |
    #  issuer: https://sso.dev.meeraspace.com

  configurationEnv: {}
    #cache_host: memcached-gcxt

  configurationEnv: {}
    # key: value

istio:
  envoyfilter:
    enabled: false

  virtualservice:
    enabled: true
    host: was
    host1: wasl
    http:
    - match:
      - uri:
          prefix: /audit
      route:
      - destination:
          host: audit-trail-service
          port:
            number: 8091

  virtualserviceGrpc:
    enabled: false

  virtualserviceGrpcMtls:
    enabled: false

envs:
  enabled: false

job:
  initdb:
    enabled: false

image:
  repository: registry.gitlab.com/target-digital-transformation/audit-trail-service/develop
  tag: 46c1232d
  pullPolicy: IfNotPresent
  # pullPolicy: Always

  ports:
  - name: tcp
    containerPort: 8080
  #- name: http
  #  containerPort: 8080
  #- name: grpc
  #  containerPort: 50051

  extraCommand: {}
  #- --grpc-address=:5001
  #- --verbose
  # - --cors-hosts=$(cors-hosts)

  ## ExtraEnv has the highest priority when there are multiple repeating envs
  extraEnv:
  ##  If you do want to specify ENV, uncomment the following
  ##  If the helm template cannot resolve the environment variable values correctly, you can add the environment variables directly to the deployment.file

    DATA_STORE_DRIVER: InternalText
    DATA_STORE_ENTITY_NAME: audit-trail
    #SERVICE_COMMIT_NO: 23.12.20

  extraENVRulehandled:

    #ENVS_HTTP_ADDR: envs.$nsPrefix-envs:9112
    
    DATA_STORE_DRIVER_URL: http://elasticsearch-master.$nsPrefix-elasticsearch-v730:9200/
    RMQ_HOST: rabbitmq.$nsPrefix-rabbitmq

service:
  type: ClusterIP
  ports:
  - port: 8091
    name: tcp
    targetPort: 8080
  #- port: 50051
  #  name: grpc
  #  targetPort: 50051

livenessProbe:
  # httpGet:
  #   path: /healthz
  #   port: 9092
  # initialDelaySeconds: 30
  # periodSeconds: 30
  # failureThreshold: 3

readinessProbe:
  # httpGet:
  #   path: /healthz
  #   port: 9092
  # initialDelaySeconds: 10
  # periodSeconds: 5
  # failureThreshold: 3

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #limits:
  # cpu: 2500m
  # memory: 2000Mi
  #requests:
  # cpu: 1000m
  # memory: 1000Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}
   #project: wasl1

tolerations:
- key: wasl1
  operator: Equal
  value: "true"
  effect: NoExecute

affinity: {}

terminationGracePeriod: 30

volumeMounts:
  ## If true,  Pod volumes to mount into the container's filesystem
  enabled: false
  volumeMounts:
    #- name: configmap
    #  mountPath: /config
    #  #subpath: CHANGEME
    #- name: ca-bundle
    #  mountPath: /etc/ssl/certs/ca-certificate.crt
    #  subPath: ca-certificate.crt
    #- name: ca-bundle
    #  mountPath: /etc/ssl/certs/java/cacerts
    #  subPath: cacerts
    #- name: audit-trail-service-hostpath-storage
    #  mountPath: /DIGITAL_TP
    #- name: audit-trail-service-large-files-hostpath-storage
    #  mountPath: /tmp/mount/
    #- name: audit-trail-service-config-pvc-mount
    #  mountPath: /config

volumes:
  ## if type is configmap, will auto use the configmap value by  `name: {{ template "APP.fullname" . }}-config`
  configmap:
    enabled: false
  #volumes:
    #- name: ca-bundle
    #  configMap:
    #    name: ca-bundle
    #- name: CNGNAME
    #  nfs:
    #    server: CNGNAME
    #    path: CNGNAME
    #- name: audit-trail-service-hostpath-storage
    #  hostPath:
    #    path: /DIGITAL_TP
    #    type: DirectoryOrCreate
    #- name: audit-trail-service-large-files-hostpath-storage
    #  hostPath:
    #    path: /DIGITAL_TP/large_files
    #    type: DirectoryOrCreate
    #- name: CNGNAME   # same to volumeMounts.name
    #  volumesvolumes:
    #    claimName: audit-trail-service-config-pvc
    #- name: ssl-certs
    # emptyDir: {}

persistentVolumeClaim1:
  ## If true,  will create/use a Persistent Volume Claim
  enabled: false
  name: audit-trail-service-config-pvc   # same to volumes.volumes.volumesvolumes.claimName
  ## supported values: "ReadOnlyMany", "ReadWriteMany", "ReadWriteOnce"
  accessModes:
    - ReadWriteOnce
  annotations: {}
  ##
  ## If you want to reuse an existing claim, you can pass the name of the PVC using
  ## the existingClaim variable
  #existingClaim: "your-claim"
  size: 1Gi
  storageClass: "nfs-client"
