{{- if .Values.sharedConfigmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- $baseUrl := .Values.global.baseUrl -}}
  {{- $nsPrefix := .Values.global.nsPrefix -}}
{{- if .Values.sharedConfigmap.configurationEnv }}
{{- range $key, $val := .Values.sharedConfigmap.configurationEnv }}
  {{ $key }}: {{ $val | quote |replace "$baseUrl" $baseUrl | replace "$nsPrefix" $nsPrefix}}
{{- end }}
{{- end -}}
{{- if .Values.sharedConfigmap.mtlsCredential }}
{{- $dot := . -}}
{{- range .Values.sharedConfigmap.mtlsCredential }}
{{ ($dot.Files.Glob (printf "Files/%s/*" .)).AsConfig | indent 2 }}
{{- end }}
{{- end -}}
{{- if .Values.sharedConfigmap.configurationFiles }}
{{- range $key, $val := .Values.sharedConfigmap.configurationFiles }}
  {{ $key }}: |-
{{- if and (kindIs "map" $val) (regexFind ".+\\.yaml$" $key) }}
{{ $val |toYaml|toString| indent 4|replace "$baseUrl" $baseUrl | replace "$nsPrefix" $nsPrefix }}
{{- else }}
{{ $val | indent 4| replace "$baseUrl" $baseUrl | replace "$nsPrefix" $nsPrefix }}
{{- end }}
{{- end }}
{{- end -}}
{{- end -}}