apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gitlabregistrykey
  labels:
    app: {{ template "APP.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: "kubernetes.io/dockercfg"
data:
{{- range .Files.Lines "Files/registrySecret.txt" }}
  {{ . }}{{ end }}