{{- $nsPrefix := .Values.global.nsPrefix -}}
{{- if .Values.servicemonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "APP.name" . }}
    release: {{ .Values.servicemonitor.matchReleaseName | default "rancher-monitoring" | quote }}
  name: {{ template "APP.name" . }}
spec:
  endpoints:
{{ toYaml .Values.servicemonitor.endpoints | indent 2 | replace "$nsPrefix" $nsPrefix }}
  namespaceSelector:
{{ toYaml .Values.servicemonitor.namespaceSelector | indent 4 | replace "$nsPrefix" $nsPrefix }}
  selector:
{{ toYaml .Values.servicemonitor.selector | indent 4 | replace "$nsPrefix" $nsPrefix }}
 
{{- end -}}